"""modify nodes

Revision ID: 00ff28485e61
Revises: f93df52f6a04
Create Date: 2024-06-14 15:49:45.196602

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00ff28485e61"
down_revision: Union[str, None] = "f93df52f6a04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nodes", sa.Column("charachter_name", sa.String(length=40), nullable=False)
    )
    op.alter_column("storys", "base_node_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("storys", "base_node_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("nodes", "charachter_name")
    # ### end Alembic commands ###
