"""modify story

Revision ID: f93df52f6a04
Revises: 17e7308e1911
Create Date: 2024-06-14 12:09:54.487152

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f93df52f6a04"
down_revision: Union[str, None] = "17e7308e1911"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("storys", sa.Column("base_node_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("storys", "base_node_id")
    # ### end Alembic commands ###
