"""modify nodes

Revision ID: 17e7308e1911
Revises: 922c9256e7df
Create Date: 2024-06-14 11:54:45.450235

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17e7308e1911"
down_revision: Union[str, None] = "922c9256e7df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("reaction_true", sa.Text(), nullable=False))
    op.add_column("nodes", sa.Column("reaction_false", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "reaction_false")
    op.drop_column("nodes", "reaction_true")
    # ### end Alembic commands ###
